[package]
name = "bot"
version = "3.0.0"
edition = "2024"

[dependencies]
resvg = "0.44"
askama = "0.12"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serenity = { version = "0.12", default-features = false, features = ["client", "gateway", "model", "rustls_backend", "builder"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
model = { git = "https://github.com/ares-hq/model.git", branch = "main", features = ["supabase"] }
